idea
safe-scan-ai/cancer-ai pull request #2
Opened 2024-08-08 20:13 UTC by wjurkowlaniec

2024-08-09 09:08 UTC, konrad0960 commented
Please make branch name reflective of the changes its trying to introduce

2024-08-09 10:03 UTC, konrad0960 requested changes
Please describe what these changes are trying to introduce, I have a feeling that a lot of this code is sketchy, not sure if its a good practice in software development in general to merge unfunctional code like this without explicitly stating what its trying to achieve or having a plan on how to make these schetches functional. My concern is especially about logic.py.

2024-08-09 10:03 UTC, konrad0960 commented on cancer_ai/__init__.py
> +# from .subnet_links import SUBNET_LINKS
I think we can delete these imports entirely

2024-08-09 10:03 UTC, konrad0960 commented on cancer_ai/validator/manager.py
> +    def get_state(self) -> dict:
shouldnt those be abstract methods implemented by the dataset/competition manager?

2024-08-09 10:03 UTC, konrad0960 commented on cancer_ai/validator/model_manager.py
> +        if "model_dir" not in self.config:
Why are we not using the general subnet template config? same value could be accessed as self.config.model_dir and defined in utils/config.py
The thing is that the whole community is used to that way of handling config parameters. Ofc we will eventually abstract those configs either with using runpod or docker, but for anyone willing to dive into the code this is the known way in Bittensor

2024-08-09 10:03 UTC, konrad0960 commented on cancer_ai/validator/model_manager.py
> +        self.hotkey_store = {}  # Now a dictionary mapping hotkeys to ModelInfo objects
Not sure if I get this comment - the "now" suggests that it was something different earlier. Are we overwriting some default subnet template properties?

2024-08-09 10:03 UTC, konrad0960 commented on cancer_ai/validator/model_manager_test.py
> +def test_load_save_model_state(model_manager: ModelManager):
I gues this test is loading stuff rather then saving right? the name of the function is quite confusing

2024-08-09 10:03 UTC, konrad0960 commented on cancer_ai/validator/model_manager_test.py
> +def test_delete_model(model_manager: ModelManager):
shouldnt unit tests handle single functionality? I knows its kinda very formal comment here, but you know, since we had in the other tests in this file some structures populated "manually" then why we are not being consistent in the approach?

2024-08-09 10:03 UTC, konrad0960 commented on cancer_ai/validator/model_manager_test.py
> +def not_test_real_downloading(model_manager: ModelManager):
I don't know this not_test naming convention - could you elaborate on this function name?

2024-08-09 10:03 UTC, konrad0960 commented on logic.py
> +from datetime import datetime
Why the file is titled logic.py? From what I can see its defining the Validator class

2024-08-09 10:03 UTC, konrad0960 commented on logic.py
> +class Validator:
Why we are not making it a child of the BaseValidator class of subnet template?

2024-08-09 10:03 UTC, konrad0960 commented on logic.py
> +        self.validator_hotkey = validator_hotkey
If we had this as a BaseValidator child then this parameter is already available and defined on the Neuron level

2024-08-09 10:03 UTC, konrad0960 commented on logic.py
> +database = {} # validator database
is it going to be a dict in memory or you want to introduce a real database here in the future?

2024-08-09 10:05 UTC, wjurkowlaniec commented on cancer_ai/validator/model_manager_test.py
> +def not_test_real_downloading(model_manager: ModelManager):
it's disabled because it does real download

2024-08-09 12:03 UTC, konrad0960 commented on cancer_ai/validator/model_manager_test.py
> +def not_test_real_downloading(model_manager: ModelManager):
so the convention is that this test is not executed that way when running the test suite etc.? then we run this test on some special ocassion or how is that working?

2024-08-13 10:19 UTC, wjurkowlaniec commented on cancer_ai/validator/model_manager.py
> +        if "model_dir" not in self.config:
lol

2024-08-13 10:19 UTC, wjurkowlaniec commented on cancer_ai/validator/model_manager_test.py
> +def test_delete_model(model_manager: ModelManager):
you have to add first to delete later, and get_state shows if it is deleted

2024-08-13 10:19 UTC, wjurkowlaniec commented on cancer_ai/validator/model_manager_test.py
> +def test_load_save_model_state(model_manager: ModelManager):
saving and loading ^^

2024-08-13 10:19 UTC, wjurkowlaniec commented on cancer_ai/validator/manager.py
> +    def get_state(self) -> dict:
done

2024-08-13 10:19 UTC, wjurkowlaniec commented on cancer_ai/validator/model_manager.py
> +        if "model_dir" not in self.config:
fixed using config

2024-08-13 10:19 UTC, wjurkowlaniec commented on cancer_ai/validator/model_manager.py
> +        self.hotkey_store = {}  # Now a dictionary mapping hotkeys to ModelInfo objects
deleted comment ^&^

2024-08-13 10:20 UTC, wjurkowlaniec commented on cancer_ai/validator/model_manager_test.py
> +def not_test_real_downloading(model_manager: ModelManager):
I used dectorator to skip test with reason description

2024-08-13 11:40 UTC, konrad0960 reviewed
strong typing adjustments in general

2024-08-13 11:40 UTC, konrad0960 commented on cancer_ai/validator/model_manager.py
> +    def delete_model(self, hotkey):
-> None

2024-08-13 11:40 UTC, konrad0960 commented on cancer_ai/validator/model_manager_test.py
> +def model_manager():
typing

2024-08-13 11:40 UTC, konrad0960 commented on cancer_ai/validator/model_manager_test.py
> +def test_add_model(model_manager: ModelManager):
typing

2024-08-13 12:15 UTC, konrad0960 approved these changes

2024-08-13 12:16 UTC, konrad0960 commented
LGBT

2024-08-13 12:16 UTC, merged